import type { CSSProperties } from 'react';

export const dictationDesignTokens = {
  colors: {
    background: '0 0% 100%',
    foreground: '222 47% 11%',
    card: '0 0% 100%',
    cardForeground: '222 47% 11%',
    popover: '0 0% 100%',
    popoverForeground: '222 47% 11%',
    primary: '211 100% 50%',
    primaryForeground: '0 0% 100%',
    secondary: '210 40% 96%',
    secondaryForeground: '222 47% 11%',
    muted: '210 40% 96%',
    mutedForeground: '215 16% 47%',
    accent: '210 40% 96%',
    accentForeground: '222 47% 11%',
    destructive: '0 72% 51%',
    destructiveForeground: '0 0% 100%',
    border: '214 32% 91%',
    input: '214 32% 91%',
    ring: '211 100% 50%',
  },
  app: {
    primaryLight: '211 100% 55%',
    primaryDark: '211 100% 45%',
    recordingRed: '0 72% 51%',
    successGreen: '142 71% 45%',
    warningOrange: '25 95% 53%',
    glassBg: 'rgba(255, 255, 255, 0.7)',
    glassBorder: 'rgba(0, 122, 255, 0.12)',
  },
  radius: {
    md: '0.5rem',
  },
};

export const dictationCssVars = {
  '--background': dictationDesignTokens.colors.background,
  '--foreground': dictationDesignTokens.colors.foreground,
  '--card': dictationDesignTokens.colors.card,
  '--card-foreground': dictationDesignTokens.colors.cardForeground,
  '--popover': dictationDesignTokens.colors.popover,
  '--popover-foreground': dictationDesignTokens.colors.popoverForeground,
  '--primary': dictationDesignTokens.colors.primary,
  '--primary-foreground': dictationDesignTokens.colors.primaryForeground,
  '--secondary': dictationDesignTokens.colors.secondary,
  '--secondary-foreground': dictationDesignTokens.colors.secondaryForeground,
  '--muted': dictationDesignTokens.colors.muted,
  '--muted-foreground': dictationDesignTokens.colors.mutedForeground,
  '--accent': dictationDesignTokens.colors.accent,
  '--accent-foreground': dictationDesignTokens.colors.accentForeground,
  '--destructive': dictationDesignTokens.colors.destructive,
  '--destructive-foreground': dictationDesignTokens.colors.destructiveForeground,
  '--border': dictationDesignTokens.colors.border,
  '--input': dictationDesignTokens.colors.input,
  '--ring': dictationDesignTokens.colors.ring,
  '--radius': dictationDesignTokens.radius.md,
  '--primary-light': dictationDesignTokens.app.primaryLight,
  '--primary-dark': dictationDesignTokens.app.primaryDark,
  '--recording-red': dictationDesignTokens.app.recordingRed,
  '--success-green': dictationDesignTokens.app.successGreen,
  '--warning-orange': dictationDesignTokens.app.warningOrange,
  '--glass-bg': dictationDesignTokens.app.glassBg,
  '--glass-border': dictationDesignTokens.app.glassBorder,
} as CSSProperties;
