import type { CSSProperties } from 'react';

export const dictationDesignTokens = {
  colors: {
    background: '210 40% 98%',
    foreground: '222 47% 11%',
    card: '0 0% 100%',
    cardForeground: '222 47% 11%',
    popover: '0 0% 100%',
    popoverForeground: '222 47% 11%',
    primary: '220 70% 48%',
    primaryForeground: '0 0% 98%',
    secondary: '210 30% 94%',
    secondaryForeground: '210 16% 12%',
    muted: '210 30% 94%',
    mutedForeground: '215 12% 45%',
    accent: '210 30% 94%',
    accentForeground: '210 16% 12%',
    destructive: '6 66% 56%',
    destructiveForeground: '0 0% 98%',
    border: '215 24% 90%',
    input: '215 24% 90%',
    ring: '220 70% 48%',
  },
  app: {
    primaryLight: '220 70% 56%',
    primaryDark: '220 70% 38%',
    recordingRed: '6 66% 56%',
    successGreen: '200 55% 40%',
    warningOrange: '25 95% 53%',
    glassBg: 'rgba(255, 255, 255, 0.78)',
    glassBorder: 'rgba(59, 130, 246, 0.18)',
  },
  radius: {
    md: '0.5rem',
  },
};

export const dictationCssVars = {
  '--background': dictationDesignTokens.colors.background,
  '--foreground': dictationDesignTokens.colors.foreground,
  '--card': dictationDesignTokens.colors.card,
  '--card-foreground': dictationDesignTokens.colors.cardForeground,
  '--popover': dictationDesignTokens.colors.popover,
  '--popover-foreground': dictationDesignTokens.colors.popoverForeground,
  '--primary': dictationDesignTokens.colors.primary,
  '--primary-foreground': dictationDesignTokens.colors.primaryForeground,
  '--secondary': dictationDesignTokens.colors.secondary,
  '--secondary-foreground': dictationDesignTokens.colors.secondaryForeground,
  '--muted': dictationDesignTokens.colors.muted,
  '--muted-foreground': dictationDesignTokens.colors.mutedForeground,
  '--accent': dictationDesignTokens.colors.accent,
  '--accent-foreground': dictationDesignTokens.colors.accentForeground,
  '--destructive': dictationDesignTokens.colors.destructive,
  '--destructive-foreground': dictationDesignTokens.colors.destructiveForeground,
  '--border': dictationDesignTokens.colors.border,
  '--input': dictationDesignTokens.colors.input,
  '--ring': dictationDesignTokens.colors.ring,
  '--radius': dictationDesignTokens.radius.md,
  '--primary-light': dictationDesignTokens.app.primaryLight,
  '--primary-dark': dictationDesignTokens.app.primaryDark,
  '--recording-red': dictationDesignTokens.app.recordingRed,
  '--success-green': dictationDesignTokens.app.successGreen,
  '--warning-orange': dictationDesignTokens.app.warningOrange,
  '--glass-bg': dictationDesignTokens.app.glassBg,
  '--glass-border': dictationDesignTokens.app.glassBorder,
} as CSSProperties;
